security:
    providers:
        main:
            entity:
                class: brutal\DbBundle\Entity\User
                property: email

    encoders:
        brutal\DbBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
            
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        
    firewalls:
        int_area:
            pattern: ^/
            anonymous: ~
            form_login: 
                login_path: login
                check_path: login_check
            logout:
                path: /logout
                target: /
    access_control:
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        - { path: ^/*, roles: ROLE_USER }